group transaction cards by date
conroyr41/Money-Manager pull request #17
Opened 2021-10-28 23:45 UTC by nader-fares

2021-10-29 23:10 UTC, plasmatical approved these changes

2021-11-01 14:59 UTC, IronWarden approved these changes

2021-11-03 15:44 UTC, conroyr41 requested changes
For some reason, this code crashes the app. When I run the code, the app opens and works fine, but when I switch to the transaction screen, the app crashes. I tested it both on an android emulator and my physical phone (which is also uses the Android OS). Have you tried testing it on the Android OS?

2021-11-04 14:45 UTC, conroyr41 commented on src/screens/TransactionLog.tsx
> +//
```suggestion

```
Looks like you have an unnecessary comment here. Please delete it.

2021-11-04 14:48 UTC, conroyr41 requested changes
It works now and I really like the changes! There is just one small issue though. When the view toggle is set to "expenses", the first group of transactions appear without a date. I will post a screenshot in discord. Other than that, the code looks great. There was just one minor correction I suggested in your code.

2021-11-05 22:45 UTC, conroyr41 approved these changes

2021-11-05 22:45 UTC, merged